import { Regulation } from '@/types'

export const regulations: Regulation[] = [
  {
    id: 'rule-1',
    titleEs: 'Cumplimiento Técnico',
    titleEn: 'Technical Compliance',
    contentEs: 'Todos los movimientos deben ejecutarse con técnica completa. Los jueces revisarán cada repetición. Movimientos incompletos no serán contabilizados.',
    contentEn: 'All movements must be performed with complete technique. Judges will review each rep. Incomplete reps will not be counted.',
    category: 'rules',
  },
  {
    id: 'rule-2',
    titleEs: 'Tiempo Límite',
    titleEn: 'Time Limit',
    contentEs: 'Amateur: 75 minutos para completar el circuito completo. Pro: 60 minutos. Los atletas que no crucen la línea de meta en su tiempo límite serán descalificados.',
    contentEn: 'Amateur: 75 minutes to complete the full circuit. Pro: 60 minutes. Athletes who do not cross the finish line within their time limit will be disqualified.',
    category: 'rules',
  },
  {
    id: 'safety-2',
    titleEs: 'Exención Médica',
    titleEn: 'Medical Waiver',
    contentEs: 'Certificado médico requerido 2 semanas antes del evento. El personal médico en sitio tiene autoridad para pausar o retirar atletas por seguridad.',
    contentEn: 'Medical certificate required 2 weeks before event. On-site medical staff has authority to pause or withdraw athletes for safety.',
    category: 'safety',
  },
  {
    id: 'penalty-1',
    titleEs: 'Falta de Técnica',
    titleEn: 'Technique Faults',
    contentEs: '1 falta de técnica = 5 segundos de penalización. 3 faltas = descalificación de la estación.',
    contentEn: '1 technique fault = 5 second penalty. 3 faults = station disqualification.',
    category: 'penalties',
  },
  {
    id: 'penalty-2',
    titleEs: 'Ayuda Externa',
    titleEn: 'Outside Assistance',
    contentEs: 'Cualquier ayuda de terceros resulta en descalificación inmediata del evento.',
    contentEn: 'Any outside assistance results in immediate event disqualification.',
    category: 'penalties',
  },
  {
    id: 'penalty-3',
    titleEs: 'Kettlebell Swings — Estándar de Movimiento',
    titleEn: 'Kettlebell Swings — Movement Standard',
    contentEs: 'La kettlebell debe subir mínimo a la altura del pecho. Una repetición mal ejecutada no cuenta (PROS). Amateur: si el equipo no completa las 30 reps, no avanzan a la siguiente sección.',
    contentEn: 'The kettlebell must reach at least chest height. A poorly executed rep does not count (PROS). Amateur: if the team does not complete 30 reps, they cannot advance to the next section.',
    category: 'penalties',
  },
  {
    id: 'penalty-4',
    titleEs: 'Farmer Carry — Kettlebell en el Suelo',
    titleEn: 'Farmer Carry — Kettlebell on the Ground',
    contentEs: 'Si la kettlebell toca el piso antes de completar una recta, el atleta deberá regresar al inicio de esa recta y repetirla.',
    contentEn: 'If the kettlebell touches the ground before completing a straight, the athlete must return to the start of that straight and repeat it.',
    category: 'penalties',
  },
  {
    id: 'penalty-5',
    titleEs: 'Running — Regla Amateur (Todos los Tramos)',
    titleEn: 'Running — Amateur Rule (All Sections)',
    contentEs: 'En la categoría amateur, ambos integrantes del equipo deben correr juntos en todos los tramos de running y cruzar la meta juntos. Separarse o cruzar la meta en momentos distintos invalida el resultado.',
    contentEn: 'In the amateur category, both team members must run together across all running sections and cross the finish line together. Separating or crossing the finish at different times invalidates the result.',
    category: 'penalties',
  },
  {
    id: 'logistics-1',
    titleEs: 'Check-In',
    titleEn: 'Check-In',
    contentEs: 'Presentarse 1 hora antes del evento.',
    contentEn: 'Arrive 1 hour before event.',
    category: 'logistics',
  },
  // {
  //   id: 'logistics-2',
  //   titleEs: 'Resultados',
  //   titleEn: 'Results',
  //   contentEs: 'Los resultados se publicarán en vivo en el sitio web. Reclamaciones de resultado deben hacerse dentro de 30 minutos de finalizar.',
  //   contentEn: 'Results published live on website. Result disputes must be filed within 30 minutes of finish.',
  //   category: 'logistics',
  // },
]
