import { Regulation } from '@/types'

export const regulations: Regulation[] = [
  {
    id: 'rule-1',
    titleEs: 'Cumplimiento Técnico',
    titleEn: 'Technical Compliance',
    contentEs: 'Todos los movimientos deben ejecutarse con técnica completa. Los jueces revisarán cada repetición. Movimientos incompletos no serán contabilizados.',
    contentEn: 'All movements must be performed with complete technique. Judges will review each rep. Incomplete reps will not be counted.',
    category: 'rules',
  },
  {
    id: 'rule-2',
    titleEs: 'Tiempo Límite',
    titleEn: 'Time Limit',
    contentEs: 'Amateur (equipos de 2): 75 minutos para completar el circuito completo. Pro (individual): 55 minutos. Los atletas que no crucen la línea de meta en su tiempo límite serán descalificados.',
    contentEn: 'Amateur (teams of 2): 75 minutes to complete the full circuit. Pro (individual): 55 minutes. Athletes who do not cross the finish line within their time limit will be disqualified.',
    category: 'rules',
  },
  {
    id: 'safety-2',
    titleEs: 'Exención Médica',
    titleEn: 'Medical Waiver',
    contentEs: 'Certificado médico requerido 2 semanas antes del evento. El personal médico en sitio tiene autoridad para pausar o retirar atletas por seguridad.',
    contentEn: 'Medical certificate required 2 weeks before event. On-site medical staff has authority to pause or withdraw athletes for safety.',
    category: 'safety',
  },
  {
    id: 'penalty-1',
    titleEs: 'Falta de Técnica',
    titleEn: 'Technique Faults',
    contentEs: '1 falta de técnica = 5 segundos de penalización. 3 faltas = descalificación de la estación.',
    contentEn: '1 technique fault = 5 second penalty. 3 faults = station disqualification.',
    category: 'penalties',
  },
  {
    id: 'penalty-2',
    titleEs: 'Ayuda Externa',
    titleEn: 'Outside Assistance',
    contentEs: 'Cualquier ayuda de terceros resulta en descalificación inmediata del evento.',
    contentEn: 'Any outside assistance results in immediate event disqualification.',
    category: 'penalties',
  },
  {
    id: 'penalty-3',
    titleEs: 'Kettlebell Swings — Estándar de Movimiento',
    titleEn: 'Kettlebell Swings — Movement Standard',
    contentEs: 'La kettlebell debe subir mínimo a la altura del pecho (swing a dos manos). En PROS: repetición mal hecha = el juez no la cuenta. En Amateur: si un integrante no completa sus 30 reps, el equipo no avanza a la final.',
    contentEn: 'The kettlebell must reach at least chest height (two-hand swing). For PROS: poorly executed rep = judge does not count it. For Amateur: if one member does not complete 30 reps, the team cannot advance to the final.',
    category: 'penalties',
  },
  {
    id: 'penalty-4',
    titleEs: 'Farmer Carry — Kettlebell en el Suelo',
    titleEn: 'Farmer Carry — Kettlebell on the Ground',
    contentEs: 'Si el KB toca el piso antes de completar una recta, el atleta deberá realizar una recta adicional de Caminata Granjero como penalización.',
    contentEn: 'If the KB touches the ground before completing a straight, the athlete must complete one additional Farmer Carry straight as a penalty.',
    category: 'penalties',
  },
  {
    id: 'penalty-5',
    titleEs: 'Running — Regla Amateur (Todos los Tramos)',
    titleEn: 'Running — Amateur Rule (All Sections)',
    contentEs: 'En la categoría amateur, ambos integrantes del equipo deben correr juntos en todos los tramos de running y cruzar la meta juntos. Separarse o cruzar la meta en momentos distintos invalida el resultado.',
    contentEn: 'In the amateur category, both team members must run together across all running sections and cross the finish line together. Separating or crossing the finish at different times invalidates the result.',
    category: 'penalties',
  },
  {
    id: 'logistics-1',
    titleEs: 'Check-In',
    titleEn: 'Check-In',
    contentEs: 'Check-In: 12:00 PM – 2:00 PM. Cierre del check-in: 2:15 PM. No se admitirán inscripciones fuera de ese horario.',
    contentEn: 'Check-In: 12:00 PM – 2:00 PM. Check-in closes: 2:15 PM. No registrations will be accepted after that time.',
    category: 'logistics',
  },
  // {
  //   id: 'logistics-2',
  //   titleEs: 'Resultados',
  //   titleEn: 'Results',
  //   contentEs: 'Los resultados se publicarán en vivo en el sitio web. Reclamaciones de resultado deben hacerse dentro de 30 minutos de finalizar.',
  //   contentEn: 'Results published live on website. Result disputes must be filed within 30 minutes of finish.',
  //   category: 'logistics',
  // },
]
