export const siteCopy = {
  es: {
    navbar: {
      home: 'Inicio',
      about: 'Acerca de',
      circuit: 'Circuito',
      categories: 'Categorías',
      register: 'Inscríbete',
      regulations: 'Regulaciones',
    },
    hero: {
      heading: 'CONQUISTA LA ÉLITE',
      subheading: 'Esto no es un juego. Es una competencia híbrida de running y entrenamiento funcional.',
      cta: 'Inscríbete Ahora',
      date: '16 de Mayo, 2025',
      location: 'Lima, Perú',
      spots: 'Cupos Limitados',
    },
    stats: {
      athletes: '1,000+',
      athletes_sub: 'atletas competidores',
      categories: '2',
      categories_sub: 'categorías de competencia',
      time: '4.8 km',
      time_sub: 'distancia total',
      format: 'Híbrido',
      format_sub: 'running + funcional',
    },
    about: {
      label: 'ACERCA DEL EVENTO',
      title: 'Una Competencia de Otro Nivel',
      description: 'Conquest Games no es un evento casual. Es una experiencia deportiva diseñada para atletas que quieren medir su límite real. Combina resistencia cardiovascular con potencia funcional en un formato competitivo de alto nivel.',
      mission_title: 'Nuestra Misión',
      mission_text: 'Promover la cultura atlética y hacer que más disciplinas deportivas sean visibles, atractivas e integradas en la comunidad competitiva — incorporando en cada edición futura una disciplina nueva o de temporada.',
    },
    why: {
      label: '¿POR QUÉ COMPETIR?',
      title: 'Razones para Unirte',
      reasons: [
        {
          title: 'Desafío Elite',
          text: 'Prueba tus límites contra los mejores atletas de la región en una competencia verdaderamente desafiante.',
        },
        {
          title: 'Comunidad',
          text: 'Forma parte de una red de atletas de alto rendimiento compartiendo valores de excelencia y superación.',
        },
        {
          title: 'Experiencia Única',
          text: 'Vive una jornada de competencia profesional con producción de clase mundial y logística impecable.',
        },
        {
          title: 'Reconocimiento',
          text: 'Gana premios, trofeos y reconocimiento dentro de la comunidad fitness de Latinoamérica.',
        },
      ],
    },
    circuit: {
      title: 'El Circuito',
      subtitle: 'Este esquema representa el flujo de las 7 estaciones de Conquest Games.',
      stages: 'Etapas del Circuito',
    },
    categories: {
      title: 'Categorías',
      subtitle: 'Competencia justa para todos los niveles',
    },
    registration: {
      title: 'Inscripción',
      subtitle: 'Completa el formulario para asegurar tu lugar',
      firstName: 'Nombre',
      lastName: 'Apellido',
      dni: 'DNI',
      email: 'Correo Electrónico',
      phone: 'Teléfono',
      age: 'Edad',
      category: 'Categoría',
      emergencyContactName: 'Nombre del Contacto de Emergencia',
      emergencyContactPhone: 'Teléfono de Emergencia',
      transferNumber: 'Número de Transferencia',
      transferNumberPlaceholder: 'Ej: TRF-123456',
      insuranceProvider: 'Proveedor de Seguro',
      insuranceProviderPlaceholder: 'Ej: Rimac, Pacifico, La Positiva',
      agreeToWaiver: 'Acepto la exención de responsabilidad',
      agreeToTerms: 'Acepto los términos y condiciones',
      submit: 'Inscribirse',
      success: 'Inscripción completada. ¡Bienvenido a Conquest Games!',
      error: 'Error en la inscripción. Intenta nuevamente.',
      validatedCount: 'inscritos validados',
    },
    eventInfo: {
      title: 'Detalles del Evento',
      date: 'Fecha',
      time: 'Hora',
      location: 'Ubicación',
      duration: 'Duración Estimada',
      capacity: 'Capacidad',
      requirements: 'Requisitos',
    },
    regulations: {
      title: 'Regulaciones',
      rules: 'Reglas',
      safety: 'Seguridad',
      penalties: 'Sanciones',
      logistics: 'Logística',
    },
    chat: {
      title: 'Asistente Conquest',
      placeholder: 'Escribe tu pregunta...',
      prompts: ['¿Cómo me inscribo?', '¿Qué categoría elijo?', '¿Cómo es el circuito?', '¿Quedan cupos?'],
    },
    nav: {
      register: 'Inscríbete',
    },
  },
  en: {
    navbar: {
      home: 'Home',
      about: 'About',
      circuit: 'Circuit',
      categories: 'Categories',
      register: 'Register',
      regulations: 'Regulations',
    },
    hero: {
      heading: 'CONQUER THE ELITE',
      subheading: 'This is not a game. It\'s a hybrid competition of running and functional fitness.',
      cta: 'Register Now',
      date: 'May 16, 2025',
      location: 'Lima, Peru',
      spots: 'Limited Spots',
    },
    stats: {
      athletes: '1,000+',
      athletes_sub: 'competing athletes',
      categories: '2',
      categories_sub: 'competition categories',
      time: '4.8 km',
      time_sub: 'total distance',
      format: 'Hybrid',
      format_sub: 'running + functional',
    },
    about: {
      label: 'ABOUT THE EVENT',
      title: 'A Competition at Another Level',
      description: 'Conquest Games is not a casual event. It\'s a sports experience designed for athletes who want to test their real limit. It combines cardiovascular endurance with functional power in a high-level competitive format.',
      mission_title: 'Our Mission',
      mission_text: 'Promote athletic culture and make more sports disciplines visible, attractive and integrated into the competitive community — incorporating a new or seasonal discipline in every future edition.',
    },
    why: {
      label: 'WHY COMPETE?',
      title: 'Reasons to Join',
      reasons: [
        {
          title: 'Elite Challenge',
          text: 'Test your limits against the best athletes in the region in a truly challenging competition.',
        },
        {
          title: 'Community',
          text: 'Join a network of high-performance athletes sharing values of excellence and personal growth.',
        },
        {
          title: 'Unique Experience',
          text: 'Experience a professional-grade competition day with world-class production and flawless logistics.',
        },
        {
          title: 'Recognition',
          text: 'Win prizes, trophies and recognition within the Latin American fitness community.',
        },
      ],
    },
    circuit: {
      title: 'The Circuit',
      subtitle: 'This diagram represents the flow of 7 stations at Conquest Games.',
      stages: 'Circuit Stages',
    },
    categories: {
      title: 'Categories',
      subtitle: 'Fair competition for all levels',
    },
    registration: {
      title: 'Registration',
      subtitle: 'Complete the form to secure your spot',
      firstName: 'First Name',
      lastName: 'Last Name',
      dni: 'ID Number',
      email: 'Email',
      phone: 'Phone',
      age: 'Age',
      category: 'Category',
      emergencyContactName: 'Emergency Contact Name',
      emergencyContactPhone: 'Emergency Contact Phone',
      transferNumber: 'Transfer Number',
      transferNumberPlaceholder: 'e.g. TRF-123456',
      insuranceProvider: 'Insurance Provider',
      insuranceProviderPlaceholder: 'e.g. Rimac, Pacifico, La Positiva',
      agreeToWaiver: 'I agree to the liability waiver',
      agreeToTerms: 'I agree to terms and conditions',
      submit: 'Register',
      success: 'Registration complete. Welcome to Conquest Games!',
      error: 'Registration error. Please try again.',
      validatedCount: 'validated registrations',
    },
    eventInfo: {
      title: 'Event Details',
      date: 'Date',
      time: 'Time',
      location: 'Location',
      duration: 'Estimated Duration',
      capacity: 'Capacity',
      requirements: 'Requirements',
    },
    regulations: {
      title: 'Regulations',
      rules: 'Rules',
      safety: 'Safety',
      penalties: 'Penalties',
      logistics: 'Logistics',
    },
    chat: {
      title: 'Conquest Assistant',
      placeholder: 'Ask a question...',
      prompts: ['How do I register?', 'Which category?', 'How does the circuit work?', 'Are there spots left?'],
    },
    nav: {
      register: 'Register',
    },
  },
}
