export const siteCopy = {
  es: {
    navbar: {
      home: 'Inicio',
      about: 'Acerca de',
      circuit: 'Circuito',
      categories: 'Categorías',
      register: 'Inscríbete',
      regulations: 'Regulaciones',
      why: 'Inscripción',
      eventInfo: 'Detalles',
    },
    hero: {
      heading: 'CONQUEST GAMES',
      subheading: 'Evento de alto rendimiento diseñado para amateurs y profesionales. Combinamos ejercicios funcionales con el running.',
      cta: 'Inscríbete Ahora',
      date: '16 de Mayo, 2025',
      location: 'Lima, Perú',
      spots: 'Cupos Limitados',
    },
    stats: {
      athletes: '1,000+',
      athletes_sub: 'atletas competidores',
      categories: '2',
      categories_sub: 'categorías de competencia',
      time: '4.8 km',
      time_sub: 'distancia total',
      format: 'Híbrido',
      format_sub: 'running + funcional',
    },
    about: {
      label: 'ACERCA DEL EVENTO',
      title: 'Una Competencia de Otro Nivel',
      description: 'El evento que reúne atletas amateur y pros en un circuito de running + funcional. Vive la experiencia, compite al máximo y demuestra tu nivel.',
      mission_title: 'Nuestra Misión',
      mission_text: 'Promover la cultura atlética y hacer que más disciplinas deportivas sean visibles, atractivas e integradas en la comunidad competitiva — incorporando en cada edición futura una disciplina nueva o de temporada.',
    },
    why: {
      label: '¿POR QUÉ COMPETIR?',
      title: 'Razones para Unirte',
      reasons: [
        {
          title: 'Para todos los niveles',
          text: 'Categorías diseñadas para amateurs (en equipo) y pros (individual), cada uno con su propio reto.',
        },
        {
          title: 'Desafío completo',
          text: 'Running + funcional en un circuito que exige resistencia, fuerza y estrategia real.',
        },
        {
          title: 'Ambiente competitivo de verdad',
          text: 'Comparte pista con atletas comprometidos, siente la presión y vive una experiencia de alto nivel.',
        },
        {
          title: 'Superación + visibilidad',
          text: 'Mide tu rendimiento, reta tus límites y forma parte de una comunidad que crece y compite en serio.',
        },
      ],
    },
    circuit: {
      title: 'El Circuito',
      subtitle: 'Este esquema representa el flujo de las 7 estaciones de Conquest Games.',
      stages: 'Etapas del Circuito',
    },
    categories: {
      title: 'Categorías',
      subtitle: 'Competencia justa para todos los niveles',
    },
    registration: {
      title: 'Inscripción',
      subtitle: 'Completa el formulario para asegurar tu lugar',
      firstName: 'Nombre',
      lastName: 'Apellido',
      dni: 'DNI',
      email: 'Correo Electrónico',
      phone: 'Teléfono',
      age: 'Edad',
      category: 'Categoría',
      emergencyContactName: 'Nombre del Contacto de Emergencia',
      emergencyContactPhone: 'Teléfono de Emergencia',
      transferNumber: 'Número de Transferencia',
      transferNumberPlaceholder: 'Ej: TRF-123456',
      insuranceProvider: 'Proveedor de Seguro',
      insuranceProviderPlaceholder: 'Ej: Rimac, Pacifico, La Positiva',
      agreeToWaiver: 'Acepto la exención de responsabilidad',
      agreeToTerms: 'Acepto los términos y condiciones',
      submit: 'Inscribirse',
      success: 'Inscripción completada. ¡Bienvenido a Conquest Games!',
      error: 'Error en la inscripción. Intenta nuevamente.',
      validatedCount: 'inscritos validados',
    },
    eventInfo: {
      title: 'Detalles del Evento',
      date: 'Fecha',
      time: 'Hora',
      location: 'Ubicación',
      duration: 'Duración Estimada',
      capacity: 'Capacidad',
      requirements: 'Requisitos',
    },
    regulations: {
      title: 'Regulaciones',
      rules: 'Reglas',
      safety: 'Seguridad',
      penalties: 'Sanciones',
      logistics: 'Logística',
    },
    chat: {
      title: 'Asistente Conquest',
      placeholder: 'Escribe tu pregunta...',
      prompts: ['¿Cómo me inscribo?', '¿Qué categoría elijo?', '¿Cómo es el circuito?', '¿Quedan cupos?'],
    },
    nav: {
      register: 'Inscríbete',
    },
  },
  en: {
    navbar: {
      home: 'Home',
      about: 'About',
      circuit: 'Circuit',
      categories: 'Categories',
      register: 'Register',
      regulations: 'Regulations',
      why: 'Register',
      eventInfo: 'Details',
    },
    hero: {
      heading: 'CONQUEST GAMES',
      subheading: 'A high-performance event designed for amateurs and professionals. We combine functional training with running.',
      cta: 'Register Now',
      date: 'May 16, 2025',
      location: 'Lima, Peru',
      spots: 'Limited Spots',
    },
    stats: {
      athletes: '1,000+',
      athletes_sub: 'competing athletes',
      categories: '2',
      categories_sub: 'competition categories',
      time: '4.8 km',
      time_sub: 'total distance',
      format: 'Hybrid',
      format_sub: 'running + functional',
    },
    about: {
      label: 'ABOUT THE EVENT',
      title: 'A Competition at Another Level',
      description: 'The event that brings together amateur and pro athletes in a running + functional circuit. Live the experience, compete at your best and prove your level.',
      mission_title: 'Our Mission',
      mission_text: 'Promote athletic culture and make more sports disciplines visible, attractive and integrated into the competitive community — incorporating a new or seasonal discipline in every future edition.',
    },
    why: {
      label: 'WHY COMPETE?',
      title: 'Reasons to Join',
      reasons: [
        {
          title: 'For all levels',
          text: 'Categories designed for amateurs (team) and pros (individual), each with their own challenge.',
        },
        {
          title: 'Complete challenge',
          text: 'Running + functional in a circuit that demands endurance, strength and real strategy.',
        },
        {
          title: 'Real competitive environment',
          text: 'Share the track with committed athletes, feel the pressure and live a high-level experience.',
        },
        {
          title: 'Progress + visibility',
          text: 'Measure your performance, push your limits and be part of a community that grows and competes seriously.',
        },
      ],
    },
    circuit: {
      title: 'The Circuit',
      subtitle: 'This diagram represents the flow of 7 stations at Conquest Games.',
      stages: 'Circuit Stages',
    },
    categories: {
      title: 'Categories',
      subtitle: 'Fair competition for all levels',
    },
    registration: {
      title: 'Registration',
      subtitle: 'Complete the form to secure your spot',
      firstName: 'First Name',
      lastName: 'Last Name',
      dni: 'ID Number',
      email: 'Email',
      phone: 'Phone',
      age: 'Age',
      category: 'Category',
      emergencyContactName: 'Emergency Contact Name',
      emergencyContactPhone: 'Emergency Contact Phone',
      transferNumber: 'Transfer Number',
      transferNumberPlaceholder: 'e.g. TRF-123456',
      insuranceProvider: 'Insurance Provider',
      insuranceProviderPlaceholder: 'e.g. Rimac, Pacifico, La Positiva',
      agreeToWaiver: 'I agree to the liability waiver',
      agreeToTerms: 'I agree to terms and conditions',
      submit: 'Register',
      success: 'Registration complete. Welcome to Conquest Games!',
      error: 'Registration error. Please try again.',
      validatedCount: 'validated registrations',
    },
    eventInfo: {
      title: 'Event Details',
      date: 'Date',
      time: 'Time',
      location: 'Location',
      duration: 'Estimated Duration',
      capacity: 'Capacity',
      requirements: 'Requirements',
    },
    regulations: {
      title: 'Regulations',
      rules: 'Rules',
      safety: 'Safety',
      penalties: 'Penalties',
      logistics: 'Logistics',
    },
    chat: {
      title: 'Conquest Assistant',
      placeholder: 'Ask a question...',
      prompts: ['How do I register?', 'Which category?', 'How does the circuit work?', 'Are there spots left?'],
    },
    nav: {
      register: 'Register',
    },
  },
}
